/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalarmachine_skijaawt_SkiaMetalCanvas */

#ifndef _Included_com_scalarmachine_skijaawt_SkiaMetalCanvas
#define _Included_com_scalarmachine_skijaawt_SkiaMetalCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scalarmachine_skijaawt_SkiaMetalCanvas
 * Method:    nInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_SkiaMetalCanvas_nInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_SkiaMetalCanvas
 * Method:    nRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_SkiaMetalCanvas_nRender
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
