/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalarmachine_skijaawt_macos_SkiaMetalCanvas */

#ifndef _Included_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
#define _Included_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_SET
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_TOP_ALIGNMENT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_TOP_ALIGNMENT 0.0f
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_CENTER_ALIGNMENT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_CENTER_ALIGNMENT 0.5f
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_BOTTOM_ALIGNMENT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_BOTTOM_ALIGNMENT 1.0f
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_LEFT_ALIGNMENT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_LEFT_ALIGNMENT 0.0f
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_RIGHT_ALIGNMENT
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_RIGHT_ALIGNMENT 1.0f
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_serialVersionUID
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_serialVersionUID -7644114512714619750LL
#undef com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_serialVersionUID
#define com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nPing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nPing
  (JNIEnv *, jclass);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nGetDevicePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nGetDevicePtr
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nGetQueuePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nGetQueuePtr
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nResize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nResize
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nGetBackWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nGetBackWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nGetBackHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nGetBackHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nBeginRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nBeginRender
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nGetDrawableTexturePtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nGetDrawableTexturePtr
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nRender
  (JNIEnv *, jobject);

/*
 * Class:     com_scalarmachine_skijaawt_macos_SkiaMetalCanvas
 * Method:    nSwapBuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scalarmachine_skijaawt_macos_SkiaMetalCanvas_nSwapBuffers
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
